define(function() {
    return {
        "properties": [{
            "name": "visiblelblName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "text",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "maxTextLength",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "visiblelblNameErr",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "textErr",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "placeholder",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "textlblName",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "textInputMode",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "keyBoardStyle",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "contentAlignmentLbl",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "contentAlignment1Txt",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "contentAlignment2Err",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "keyboardActionLabel",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "visibleofTxtFiled",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }, {
            "name": "minCharLen",
            "enumerable": true,
            "configurable": false,
            "writable": true
        }],
        "apis": [],
        "events": ["onDone", "onEndEditing", "onValidationSuccess", "onVlidationFailuer"]
    }
});